apiVersion: console.openshift.io/v1
kind: QuickStarts
metadata:
  name: openshift-cost-management
  externalDocumentation: true
spec:
  version: 0.1
  type:
    text: Documentation
    color: orange
  displayName: Analyze your cost data
  icon: 
  description: Analyze cloud and container cost data to accurately track and manage IT infrastructure spending.
  link:
    href: https://docs.redhat.com/en/documentation/cost_management_service/1-latest/observe-con_analyze_your_cost_data
    text: View documentation
