---
apiVersion: console.openshift.io/v1
kind: QuickStarts
metadata:
  name: edge-custom-images
  externalDocumentation: true
spec:
  version: 0.1
  type:
    text: Documentation
    color: orange
  displayName: Deploying and managing RHEL systems in hybrid clouds
  icon: ~
  description: Create a customized image and upload the image to target cloud environments.
  link:
    href: https://docs.redhat.com/en/documentation/red_hat_lightspeed/1-latest/html/deploying_and_managing_rhel_systems_in_hybrid_clouds/index
    text: View documentation
