apiVersion: console.openshift.io/v1
kind: QuickStarts
metadata:
  name: iam-two-factor-auth
  externalDocumentation: true
spec:
  version: 0.1
  type:
    text: Documentation
    color: orange
  displayName: Secure Red Hat user accounts with two-factor authentication (2FA)
  icon: ~
  description: Configure organization-wide two-factor authentication.
  link:
    href: https://docs.redhat.com/en/documentation/red_hat_hybrid_cloud_console/1-latest/secure-con_ciam_2fa_about
    text: View documentation
