apiVersion: console.openshift.io/v1
kind: QuickStarts
metadata:
  name: openshift-cost-models
  externalDocumentation: true
spec:
  version: 0.1
  type:
    text: Documentation
    color: orange
  displayName: Reflect real-world cloud costs
  icon: 
  description: Configure cost models so the software accurately mirrors the specific pricing and discount structures of their cloud providers.
  link:
    href: https://docs.redhat.com/en/documentation/cost_management_service/1-latest/configure-cost_models
    text: View documentation
