apiVersion: console.openshift.io/v1
kind: QuickStarts
metadata:
  name: openshift-cost-tagging
  externalDocumentation: true
spec:
  version: 0.1
  type:
    text: Documentation
    color: orange
  displayName: Allocate costs to business units
  icon: 
  description: Use tagging to organize resources, allowing the user to assign specific costs to the correct departments, projects, or teams.
  link:
    href: https://docs.redhat.com/en/documentation/cost_management_service/1-latest/configure-con_allocate_costs_to_business_units
    text: View documentation
