apiVersion: console.openshift.io/v1
kind: QuickStarts
metadata:
name: subs-data-driven-efficiency
externalDocumentation: true
spec:
version: 0.1
type:
  text: Documentation
  color: orange
displayName: Make informed decisions about subscriptions
icon: ~
description: Subscription services enable data-driven efficiency by identifying utilization patterns.
link:
  href:  https://www.redhat.com/en/resources/gain-data-driven-efficiency-overview
  text: View documentation