apiVersion: console.openshift.io/v1
kind: QuickStarts
metadata:
  name: secondary-testing-new-new
  tags:
    - kind: bundle
      value: insights
    - kind: content
      value: documentation
    - kind: product-families
      value: openshift
    - kind: product-families
      value: subscriptions-services
    - kind: use-case
      value: spend-management
    - kind: use-case
      value: system-configuration
  externalDocumentation: true
spec:
  version: 0.1
  displayName: Testing new quickstart
  icon: ~
  description: Configure cost models so the software accurately mirrors the
    specific pricing and discount structures of their cloud providers.
  type:
    text: Documentation
    color: orange
  link:
    text: View documentation
    href: https://docs.redhat.com/en/documentation/cost_management_service/1-latest/configure-cost_models
