FROM registry.access.redhat.com/ubi9/go-toolset:1.26.2-1779886993 AS builder
WORKDIR $GOPATH/src/mypackage/myapp/
COPY go.mod go.mod
COPY go.sum go.sum
COPY Makefile Makefile
COPY oapi-codegen.yaml oapi-codegen.yaml
COPY main.go main.go
COPY spec spec
COPY pkg pkg
COPY cmd cmd
COPY config config
COPY docs docs
ENV GO111MODULE=on
ENV GOTOOLCHAIN=go1.26.5
USER root
RUN go get -d -v
RUN CGO_ENABLED=0 go build -buildvcs=false -o /go/bin/git-service cmd/git-service/main.go

FROM registry.access.redhat.com/ubi9-minimal:latest

RUN microdnf install -y git && microdnf clean all

COPY --from=builder /go/bin/git-service /usr/bin

USER 1001

CMD ["git-service"]
EXPOSE 8001
