apiVersion: console.openshift.io/v1
kind: QuickStarts
metadata:
  name: openshift-source-ocp
  externalDocumentation: true
spec:
  version: 0.1
  type:
    text: Documentation
    color: orange
  displayName: "Integrate OpenShift Container Platform data with cost management"
  icon: 
  description: Consolidate container-specific costs into the broader cost management view.
  link:
    href: https://docs.redhat.com/en/documentation/cost_management_service/1-latest/integrate-integrating_os
    text: View documentation
