apiVersion: console.openshift.io/v1
kind: QuickStarts
metadata:
  name: openshift-source-azure
  externalDocumentation: true
spec:
  version: 0.1
  type:
    text: Documentation
    color: orange
  displayName: "Integrate Microsoft Azure data with cost management"
  icon: 
  description: Connect accounts from Microsoft Azure to see a unified financial picture.
  link:
    href: https://docs.redhat.com/en/documentation/cost_management_service/1-latest/integrate-azure_integration
    text: View documentation
