---
apiVersion: console.openshift.io/v1
kind: QuickStarts
metadata:
  name: edge-related-docs
  externalDocumentation: true
spec:
  version: 0.1
  type:
    text: Documentation
    color: orange
  displayName: Related documentation for edge management
  icon: ~
  description: A complete list of documentation related to edge management.
  link:
    href: https://access.redhat.com/documentation/en-us/edge_management
    text: View documentation
