apiVersion: console.openshift.io/v1
kind: QuickStarts
metadata:
  name: getting-started-with-automation-hub
  tags:
    - kind: bundle
      value: ansible
    - kind: content
      value: documentation
    - kind: product-families
      value: ansible
    - kind: use-case
      value: automation
  externalDocumentation: true
spec:
  version: 0.1
  displayName: Getting started with automation hubs
  icon: ~
  description: Configure automation hub as your default server for Ansible
    collections content.
  type:
    text: Documentation
    color: orange
  link:
    text: View documentation
    href: https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/getting_started_with_ansible_automation_platform/index
