apiVersion: console.openshift.io/v1
kind: QuickStarts
metadata:
  name: hcs-getting-started
  externalDocumentation: true
spec:
  version: 0.1
  type:
    text: Documentation
    color: orange
  displayName: Get started with Hybrid Committed Spend
  icon: ~
  description: Track your cloud spend across different hyperscalers
  link:
    href: https://docs.redhat.com/en/documentation/hybrid_committed_spend/1-latest/html/getting_started_with_hybrid_committed_spend
    text: View documentation
