---
apiVersion: console.openshift.io/v1
kind: QuickStarts
metadata:
  name: edge-manage-systems
  externalDocumentation: true
spec:
  version: 0.1
  type:
    text: Documentation
    color: orange
  displayName: Working with systems in the edge management application
  icon: ~
  description: Group, connect, and manage edge systems after registering them with the edge management console.
  link:
    href: https://access.redhat.com/documentation/en-us/edge_management/2022/html-single/working_with_systems_in_the_edge_management_application/index
    text: View documentation
