apiVersion: console.openshift.io/v1
kind: QuickStarts
metadata:
  name: settings-configuring-cloud-integrations
  externalDocumentation: true
spec:
  version: 0.1
  type:
    text: Documentation
    color: orange
  displayName: Manage cloud integrations with Red Hat services
  icon: ~
  description: Integrate external infrastructure with the console to share data with Red Hat services.
  link:
    href: https://docs.redhat.com/en/documentation/red_hat_hybrid_cloud_console/1-latest/integrate-integrate_external_infrastructure_with_rh_services
    text: View documentation
