apiVersion: console.openshift.io/v1
kind: QuickStarts
metadata:
  name: openshift-cost-management-access
  externalDocumentation: true
spec:
  version: 0.1
  type:
    text: Documentation
    color: orange
  displayName: Secure sensitive financial information
  icon: 
  description: Limit access to cost management resources to ensure only authorized personnel can view organizational spending.
  link:
    href: https://docs.redhat.com/en/documentation/cost_management_service/1-latest/configure-limiting_access
    text: View documentation
