apiVersion: console.openshift.io/v1
kind: QuickStarts
metadata:
  name: openshift-cost-explorer
  externalDocumentation: true
spec:
  version: 0.1
  type:
    text: Documentation
    color: orange
  displayName: Visualize spending trends
  icon: 
  description: Utilize the Cost Explorer to create visual representations of data, making it easier to identify spikes or trends in spending.
  link:
    href: https://docs.redhat.com/en/documentation/cost_management_service/1-latest/observe-cost_explorer
    text: View documentation
