{
 "title": "quickstarts",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "2000+ms Response count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(api_3scale_gateway_api_time_bucket{exported_service=\"quickstarts\",le=\"2000\"})\n/\nsum(api_3scale_gateway_api_time_bucket{exported_service=\"quickstarts\",le=\"+Inf\"})"
    }
   ]
  },
  {
   "title": "2000ms+ Response latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(api_3scale_gateway_api_time_bucket{exported_service=\"quickstarts\", le=\"2000\"}) / sum(api_3scale_gateway_api_time_bucket{exported_service=\"quickstarts\", le=\"+Inf\"})"
    }
   ]
  },
  {
   "title": "Responses by status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(quickstarts_responses[5m])) by (code)"
    }
   ]
  },
  {
   "title": "Non 2xx responses",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(quickstarts_responses{code=\"5xx\"} / quickstarts_responses)"
    }
   ]
  }
 ]
}