apiVersion: console.openshift.io/v1
kind: QuickStarts
metadata:
  name: full-test-pull-request
  tags:
    - kind: bundle
      value: insights
    - kind: content
      value: quickstart
spec:
  version: 0.1
  displayName: Full Test Pull Request
  icon: ~
  description: This is a sample description. This text appears on the card in the catalog.
  type:
    text: Quick start
    color: green
  durationMinutes: 10
  introduction: |
    Welcome to the tutorial!
    This text appears in the side panel when you start the quick start.
  tasks:
    - title: First Task
      description: |
        This is the instruction for the first task.
        1. Click on the "Home" button.
        2. Navigate to the "Overview" page.
      review:
        instructions: |
          Did you see the Overview page load?
        failedTaskHelp: |
          If the page didn't load, try refreshing.
