apiVersion: console.openshift.io/v1
kind: QuickStarts
metadata:
  name: settings-configuring-notifications-integrations
  externalDocumentation: true
spec:
  version: 0.1
  type:
    text: Documentation
    color: orange
  displayName: Configure notifications for console services
  icon: ~
  description: Customize your settings to receive event-triggered notifications for your services. 
  link:
    href: https://docs.redhat.com/en/documentation/red_hat_hybrid_cloud_console/1-latest/observe-configure_notifications_hcc_services
    text: View documentation
