apiVersion: console.openshift.io/v1
kind: QuickStarts
metadata:
  name: openshift-source-aws
  externalDocumentation: true
spec:
  version: 0.1
  type:
    text: Documentation
    color: orange
  displayName: "Integrate Amazon Web Services data with cost management"
  icon: 
  description: Connect accounts from Amazon Web Services (AWS) to see a unified financial picture.
  link:
    href: https://docs.redhat.com/en/documentation/cost_management_service/1-latest/integrate-integrate_amazon_web_services_data_with_cost_management
    text: View documentation
